# Generated by Django 4.1.6 on 2023-04-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_room_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_brons', to='main.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_rooms', to='main.service'),
        ),
    ]
